### ISSUE TITLE
Next Task #2

### ISSUE THREAD

**Issue by Frankofoedu** [Uchenna-eucharia/tip-calculator1#1]
I dont want this calculator to accept any kind of value. Like i dont want to put "abbc" as my bill amount. Only numbers should be accepted.

SO the next task is for you to show an error message if i put in anything that is not an integer.

Show me the error in an alert pop up

**Comment by Uchenna-eucharia** [comment]
Nan can be what pops up right?

**Comment by Frankofoedu** [comment]
No. If it is Nan, find a way to display something else.

Imagine an error happened on your whatsapp app, should the original error message show? No. EVeryday multiple apps on your phone encounter different erros, but you wont even know, cos they will tell you one generic message like: "An error occured" "Please try again later".

So create your own error message and display it

**Comment by Frankofoedu** [comment]
I think commit b7a12e9e5530862ba6d8933b0e9bf0c7e0f3f849 has fixed this task
